import { CustomerProfile, Customer360Read, GlobalAnalytics } from '../types/api';

export const MOCK_CUSTOMERS: CustomerProfile[] = [
  {
    id: 'c101',
    external_customer_id: 'CUST-1001',
    first_name: 'Elena',
    last_name: 'Rostova',
    email: 'elena.rostova@enterprise.com',
    phone: '+1 (555) 234-8901',
    age: 38,
    gender: 'Female',
    acquisition_channel: 'Paid Search',
    customer_status: 'At-Risk',
    created_at: '2025-01-15T10:30:00Z',
  },
  {
    id: 'c102',
    external_customer_id: 'CUST-1002',
    first_name: 'Marcus',
    last_name: 'Vance',
    email: 'marcus.vance@techcorp.io',
    phone: '+1 (555) 876-5432',
    age: 44,
    gender: 'Male',
    acquisition_channel: 'Direct organic',
    customer_status: 'VIP / Active',
    created_at: '2024-11-20T08:15:00Z',
  },
  {
    id: 'c103',
    external_customer_id: 'CUST-1003',
    first_name: 'Aarav',
    last_name: 'Sharma',
    email: 'aarav.sharma@nexus.in',
    phone: '+91 98765 43210',
    age: 31,
    gender: 'Male',
    acquisition_channel: 'Partner Referral',
    customer_status: 'Dormant',
    created_at: '2025-03-04T12:00:00Z',
  },
  {
    id: 'c104',
    external_customer_id: 'CUST-1004',
    first_name: 'Sophia',
    last_name: 'Chen',
    email: 'sophia.chen@global.org',
    phone: '+1 (555) 432-1098',
    age: 29,
    gender: 'Female',
    acquisition_channel: 'Social Campaign',
    customer_status: 'At-Risk',
    created_at: '2025-06-18T16:40:00Z',
  },
  {
    id: 'c105',
    external_customer_id: 'CUST-1005',
    first_name: 'Devon',
    last_name: 'Booker',
    email: 'devon.booker@velocity.com',
    phone: '+1 (555) 654-3210',
    age: 35,
    gender: 'Male',
    acquisition_channel: 'Email Campaign',
    customer_status: 'Active',
    created_at: '2025-08-12T09:00:00Z',
  },
];

export const getMockCustomer360 = (id: string): Customer360Read => {
  const profile = MOCK_CUSTOMERS.find((c) => c.id === id || c.external_customer_id === id) || MOCK_CUSTOMERS[0];
  const isAtRisk = profile.customer_status.toLowerCase().includes('risk') || profile.id === 'c101';

  return {
    profile,
    features: {
      customer_id: profile.id,
      recency_days: isAtRisk ? 42 : 3,
      frequency_count: isAtRisk ? 14 : 38,
      monetary_value: isAtRisk ? 42500 : 124000,
      days_inactive: isAtRisk ? 42 : 3,
      engagement_score: isAtRisk ? 0.35 : 0.94,
      cart_abandonment_count: isAtRisk ? 3 : 0,
      average_order_value: isAtRisk ? 3035.71 : 3263.15,
      estimated_clv: isAtRisk ? 68500 : 185000,
      updated_at: new Date().toISOString(),
    },
    segments: [
      { id: 'seg1', name: 'High Value', description: 'Lifetime spend > $30k' },
      { id: 'seg2', name: isAtRisk ? 'At Risk of Churn' : 'VIP Champions' },
    ],
    predictions: {
      churn: {
        model_name: 'customer360_unified_trained_artifacts',
        model_version: 'v1.0.0',
        prediction_type: 'churn',
        score: isAtRisk ? 0.784 : 0.042,
        predicted_class: isAtRisk ? 'high_risk' : 'low_risk',
        confidence: 0.892,
        created_at: new Date().toISOString(),
      },
      purchase_propensity: {
        model_name: 'customer360_unified_trained_artifacts',
        model_version: 'v1.0.0',
        prediction_type: 'purchase_propensity',
        score: isAtRisk ? 0.245 : 0.925,
        predicted_class: isAtRisk ? 'low_intent' : 'high_intent',
        confidence: 0.815,
        created_at: new Date().toISOString(),
      },
      clv: {
        model_name: 'customer360_unified_trained_artifacts',
        model_version: 'v1.0.0',
        prediction_type: 'clv',
        score: isAtRisk ? 68500 : 185000,
        predicted_class: 'high_value',
        confidence: 0.91,
        created_at: new Date().toISOString(),
      },
    },
    shap_drivers: isAtRisk
      ? [
          {
            feature_name: 'recency_days',
            feature_value: 42,
            contribution: 0.34,
            rank: 1,
            direction: 'positive',
            reason: 'Customer has not purchased for 42 days.',
          },
          {
            feature_name: 'cart_abandonment_count',
            feature_value: 3,
            contribution: 0.21,
            rank: 2,
            direction: 'positive',
            reason: '3 high-value cart abandonments recorded.',
          },
        ]
      : [
          {
            feature_name: 'frequency_count',
            feature_value: 38,
            contribution: -0.42,
            rank: 1,
            direction: 'negative',
            reason: 'High order frequency keeps churn risk low.',
          },
        ],
    next_best_action: isAtRisk
      ? {
          id: `nba_${profile.id}`,
          action: 'Retention VIP Concierge Pass & Re-engagement Campaign',
          action_type: 'RETENTION_DISCOUNT',
          reason: 'High churn risk (78.4%) paired with high CLV and abandoned carts.',
          recommended_offer: '20% VIP Re-engagement Discount',
          preferred_channel: 'WhatsApp',
          preferred_category: 'Electronics',
          priority: 'high',
          score: 0.92,
          timing: 'Within 24 hours',
          objective: 'Prevent immediate high-value churn',
          status: 'PENDING',
          created_at: new Date().toISOString(),
        }
      : {
          id: `nba_${profile.id}`,
          action: 'Enterprise Tier Upsell & Exclusive Preview',
          action_type: 'UPSELL',
          reason: 'High purchase intent (92.5%) and active account usage.',
          recommended_offer: 'Pro Analytics Annual Upgrade',
          preferred_channel: 'Email',
          preferred_category: 'Electronics',
          priority: 'medium',
          score: 0.78,
          timing: 'Next 3 days',
          objective: 'Expand Account Value',
          status: 'PENDING',
          created_at: new Date().toISOString(),
        },
    recent_transactions: [
      {
        id: `tx_${profile.id}_1`,
        customer_id: profile.id,
        reference_id: 'REF-889021',
        product_name: 'Customer360 Pro License Annual',
        category: 'Electronics',
        amount: isAtRisk ? 14500 : 45000,
        quantity: 1,
        transaction_time: '2026-07-29T11:20:00Z',
        channel: 'Web Portal',
        status: 'COMPLETED',
      },
    ],
    recent_interactions: [
      {
        id: `int_${profile.id}_1`,
        customer_id: profile.id,
        event_type: isAtRisk ? 'cart_abandonment' : 'dashboard_active',
        event_value: isAtRisk ? 'Cart total: $3,200.00' : 'Exported Executive Report',
        metadata_json: { category: 'Electronics' },
        timestamp: new Date().toISOString(),
      },
    ],
    action_history: [],
    action_feedback: {
      total_actions: 2,
      pending_actions: 1,
      executed_actions: 1,
      dismissed_actions: 0,
      delivered_count: 1,
      opened_count: 1,
      clicked_count: 1,
      converted_count: 1,
      delivery_rate: 1.0,
      open_rate: 1.0,
      click_rate: 1.0,
      ctr: 1.0,
      conversion_rate: 1.0,
      total_revenue: 4800,
      average_revenue_per_converted: 4800,
    },
  };
};

export const MOCK_GLOBAL_ANALYTICS: GlobalAnalytics = {
  total_actions: 142,
  outcomes_recorded: 118,
  delivered_count: 118,
  opened_count: 94,
  clicked_count: 68,
  converted_count: 42,
  delivery_rate: 1.0,
  open_rate: 0.796,
  click_rate: 0.576,
  ctr: 0.723,
  conversion_rate: 0.356,
  total_attributed_revenue: 184500,
  average_revenue_per_converted: 4392.85,
};
