"""Initial Customer360 Schema

Revision ID: f5ff01787cf9
Revises: 
Create Date: 2026-09-09 21:35:49.449253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = 'f5ff01787cf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('acquisition_channel', sa.String(length=100), nullable=True),
    sa.Column('customer_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_status'), 'customers', ['customer_status'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_external_customer_id'), 'customers', ['external_customer_id'], unique=True)
    op.create_table('model_runs',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_model_name'), 'model_runs', ['model_name'], unique=False)
    op.create_table('segments',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_name'), 'segments', ['name'], unique=True)
    op.create_table('actions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('offer', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('timing', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('objective', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_action_type'), 'actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_actions_created_at'), 'actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_actions_customer_id'), 'actions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_actions_status'), 'actions', ['status'], unique=False)
    op.create_table('customer_features',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('recency_days', sa.Integer(), nullable=False),
    sa.Column('frequency_count', sa.Integer(), nullable=False),
    sa.Column('monetary_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('days_inactive', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('cart_abandonment_count', sa.Integer(), nullable=False),
    sa.Column('purchase_frequency', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('average_order_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_clv', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extra_features', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_features_customer_id'), 'customer_features', ['customer_id'], unique=True)
    op.create_table('customer_segments',
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('segment_id', app.models.base.GUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'segment_id')
    )
    op.create_table('interactions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_customer_id'), 'interactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_interactions_event_type'), 'interactions', ['event_type'], unique=False)
    op.create_index(op.f('ix_interactions_timestamp'), 'interactions', ['timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('model_run_id', app.models.base.GUID(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('predicted_class', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_customer_id'), 'predictions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_type'), 'predictions', ['prediction_type'], unique=False)
    op.create_table('transactions',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('customer_id', app.models.base.GUID(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=True)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_time'), 'transactions', ['transaction_time'], unique=False)
    op.create_table('action_outcomes',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('action_id', app.models.base.GUID(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('opened', sa.Boolean(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('churned', sa.Boolean(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('outcome_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_outcomes_action_id'), 'action_outcomes', ['action_id'], unique=True)
    op.create_table('explanations',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('prediction_id', app.models.base.GUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('contribution', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('explanation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_feature_name'), 'explanations', ['feature_name'], unique=False)
    op.create_index(op.f('ix_explanations_prediction_id'), 'explanations', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explanations_prediction_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_feature_name'), table_name='explanations')
    op.drop_table('explanations')
    op.drop_index(op.f('ix_action_outcomes_action_id'), table_name='action_outcomes')
    op.drop_table('action_outcomes')
    op.drop_index(op.f('ix_transactions_transaction_time'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_predictions_prediction_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_customer_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_interactions_timestamp'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_event_type'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_customer_id'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('customer_segments')
    op.drop_index(op.f('ix_customer_features_customer_id'), table_name='customer_features')
    op.drop_table('customer_features')
    op.drop_index(op.f('ix_actions_status'), table_name='actions')
    op.drop_index(op.f('ix_actions_customer_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_created_at'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_type'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_segments_name'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_model_runs_model_name'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_customers_external_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_status'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
